#ifndef ASEC_SIMPLEX_GLOBAL_H
#define ASEC_SIMPLEX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ASEC_SIMPLEX_LIBRARY)
#  define ASEC_SIMPLEXSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ASEC_SIMPLEXSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ASEC_SIMPLEX_GLOBAL_H
